# Semana 11 — Integração Python e SQL: Instalação, Configuração e Primeiros Passos

Nesta semana você conecta o Python direto a um banco de dados e executa comandos SQL a partir do seu próprio código — sem precisar abrir um programa de banco de dados separado toda vez.

**⚠️ Este notebook precisa rodar no VS Code local (Windows), não no Google Colab.** O motivo é simples: uma das instalações desta semana é um programa do Windows (o driver ODBC do SQLite), e o Google Colab não permite instalar programas do seu computador — ele roda numa máquina na nuvem, não na sua.

### 🧭 De onde você vem

Nas Semanas 08 a 10 você aprendeu SQL dentro de um banco de dados relacional — consultas, filtros, joins, funções e operações de CRUD (Create, Read, Update, Delete), sempre escrevendo os comandos direto numa ferramenta de banco de dados. A partir de agora, esses mesmos comandos SQL vão ser disparados **pelo seu código Python** — é a integração entre as duas linguagens que qualquer sistema real usa no dia a dia.

## Passo 0 — Preparando seu computador (faça isso só uma vez)

O seu computador ainda não tem nada instalado para o Python conversar com um banco de dados. Antes de qualquer código de verdade, você precisa instalar 2 coisas:

1. A biblioteca **`pyodbc`** — o pacote Python que sabe conversar com bancos de dados através do padrão ODBC.
2. O **driver ODBC do SQLite** — um programa do Windows que ensina o seu computador a entender arquivos `.sqlite`/`.db` através desse mesmo padrão ODBC.

Vamos ver o que acontece se você tentar usar o `pyodbc` sem ele estar instalado.

In [ ]:
import pyodbc

O erro `ModuleNotFoundError: No module named 'pyodbc'` significa exatamente o que está escrito: o Python não encontrou essa biblioteca porque ela ainda não foi instalada no seu computador. É um erro normal e esperado agora — resolve-se com uma instalação, não com uma correção de código.

Instale a biblioteca rodando a célula abaixo:

In [ ]:
%pip install pyodbc

Agora rode a importação de novo — dessa vez sem erro:

In [ ]:
import pyodbc

print("pyodbc instalado com sucesso, versão:", pyodbc.version)

### Instalando o driver ODBC do SQLite

A biblioteca `pyodbc` já está pronta, mas ela sozinha não sabe conversar com nenhum banco específico — ela precisa de um **driver** para cada tipo de banco (um driver para SQLite, outro para SQL Server, outro para MySQL, etc.). Diferente do `pyodbc`, o driver não se instala com `pip` — ele é um programa do Windows. Siga esse passo a passo:

1. Acesse **http://www.ch-werner.de/sqliteodbc/** no seu navegador.
2. Baixe o instalador de **64 bits** — o nome do arquivo é `sqliteodbc_X.X.exe` (sem "_w32" no nome; a versão de 32 bits tem "_w32" no nome do arquivo — é o erro mais comum nesta instalação, então confira antes de baixar).
3. Execute o arquivo baixado e siga o instalador clicando em "Next" até "Finish" (as opções padrão já servem).
4. Feche o VS Code completamente e abra de novo (ou pelo menos reinicie o terminal), para o Windows reconhecer o driver novo.

Depois de instalar, rode a célula abaixo para conferir se o driver apareceu:

In [ ]:
import pyodbc

print(pyodbc.drivers())

Procure **"SQLite3 ODBC Driver"** na lista impressa acima. Se ele aparecer, a instalação funcionou e você não precisa repetir esse Passo 0 de novo em nenhum outro notebook desta semana.

Se não aparecer:
1. Reinicie o computador (não só o VS Code) e rode a célula de novo.
2. Se ainda assim não aparecer, o mais provável é ter baixado a versão de 32 bits (`_w32`) por engano — volte ao passo anterior, baixe a versão de 64 bits e instale de novo.

✅ Computador configurado. Os arquivos de banco de dados que você vai usar nesta semana (`salarios.sqlite` e `chinook.db`) já estão na pasta `dataset/`, ao lado deste notebook.

## Passo 1 — Por que integrar Python e SQL?

A integração entre Python e SQL permite executar comandos SQL diretamente pelo seu código Python, dentro do banco de dados. Isso possibilita pegar o resultado de uma consulta SQL e já trazer esse resultado pronto para dentro de uma análise no Python, sem sair do seu script.

Para você acompanhar sem se preocupar em instalar um banco de dados completo, esta semana usa o **SQLite** — o mesmo banco de dados mais simples que você já viu em semanas anteriores — e a biblioteca **`pyodbc`**, que funciona com a mesma estrutura de código para vários outros bancos de dados (SQL Server, MySQL, Oracle, entre outros). Isso significa que o que você aprender aqui vale para qualquer um desses bancos, trocando só o driver — **guarde essa ideia, porque ela vai explicar uma escolha estranha lá no Passo 4.**

**Quando faz sentido usar Python + SQL, e quando só o SQL já basta?**
- Só SQL: quando você só precisa consultar ou alterar dados diretamente na ferramenta do banco de dados.
- Python + SQL: quando um sistema (uma automação, uma análise, um aplicativo) precisa ler ou escrever no banco sozinho, sem alguém abrindo uma ferramenta manualmente — inclusive para criar o próprio banco de dados por código.

## Passo 2 — Conectando ao banco de dados com pyodbc

Para o Python conversar com qualquer banco através do `pyodbc`, o caminho é sempre o mesmo, em 3 etapas: **conectar → criar um cursor → executar comandos SQL**.

O primeiro passo é montar os dados de conexão. Cada banco de dados pede um driver diferente (por isso o `pyodbc.drivers()` do Passo 0 é útil — ele mostra os drivers já instalados no seu computador):

```
dados_conexao = ("Driver={Seu_Driver};"
                "Server=SeuServidor;"
                "Database=NomeDoBanco;")
```

Repare que só o `Driver` fica entre chaves `{ }` — isso é uma exigência do próprio padrão ODBC, porque nomes de driver costumam ter espaço no meio (como `SQLite3 ODBC Driver`), e as chaves marcam onde o nome do driver começa e termina. `Server` e `Database` não precisam disso.

Se o banco pedisse login e senha, o formato ganharia mais duas partes: `"UID=SeuLogin;"` e `"PWD=SuaSenha;"`. No nosso caso, o SQLite não usa login nem senha — só o caminho do arquivo.

**E o `Server=localhost`, se o SQLite nem tem servidor?** Diferente do PostgreSQL das Semanas 08-10 (onde existia um serviço rodando e `localhost` significava algo real), o SQLite é um banco **sem servidor** — é só um arquivo. O campo `Server` continua ali porque o formato de conexão do ODBC exige ele preenchido, mas para o SQLite ele não tem efeito nenhum — quem importa de verdade é o `Database`, com o caminho do arquivo.

In [ ]:
import pyodbc

dados_conexao = ("Driver={SQLite3 ODBC Driver};"
            "Server=localhost;"
            "Database=dataset/salarios.sqlite;")

conexao = pyodbc.connect(dados_conexao)
print("Conexão bem sucedida")

Com a conexão aberta, o próximo passo é criar o que o `pyodbc` chama de **cursor** — o objeto responsável por executar os comandos SQL dentro dessa conexão.

In [ ]:
cursor = conexao.cursor()

Agora você já pode executar comandos SQL através do cursor. Existem 2 formas de trazer o resultado:

1. `cursor.execute("COMANDO_SQL")` + `cursor.fetchall()` — executa o comando e devolve os resultados como uma lista de tuplas.
2. `pd.read_sql("COMANDO_SQL", conexao)` — executa o mesmo comando e já devolve o resultado pronto como um DataFrame do Pandas.

Vamos usar a primeira forma para trazer as 10 primeiras linhas da tabela `Salaries` (a segunda forma aparece no Passo 4):

In [ ]:
cursor.execute("SELECT * FROM Salaries")
valores = cursor.fetchall()
print(valores[:10])

Depois de terminar de usar o banco, sempre feche o cursor e a conexão — isso libera o arquivo do banco de dados para outros programas (e evita erros de "arquivo em uso" numa próxima tentativa de conexão).

In [ ]:
cursor.close()
conexao.close()

## Passo 3 — Inserindo dados no banco de dados (Create)

Além de consultar (Read), o Python também pode criar registros novos dentro do banco — o C do CRUD. Desta vez a conexão aponta para outro arquivo, o `chinook.db`, um banco de dados de uma loja de mídia digital (álbuns, artistas, faixas).

In [ ]:
import pyodbc

dados_conexao = ("Driver={SQLite3 ODBC Driver};Server=localhost;Database=dataset/chinook.db")

conexao = pyodbc.connect(dados_conexao)
cursor = conexao.cursor()

O comando SQL `INSERT INTO` cria uma linha nova numa tabela. Abaixo, um álbum novo é cadastrado na tabela `albums`, associado ao artista de `ArtistId` 4 (Alanis Morissette, já cadastrada na tabela `artists`).

Depois do `INSERT`, é obrigatório salvar a alteração de fato no arquivo do banco — sem isso, ela fica só na memória. Tanto `conexao.commit()` quanto `cursor.commit()` fazem exatamente essa mesma coisa no `pyodbc` (o cursor só repassa o pedido pra conexão) — este material usa sempre `conexao.commit()`, pra não ter dúvida de qual dos dois usar.

In [ ]:
cursor.execute('''
INSERT INTO albums (Title, ArtistId)
VALUES
('Lira Rock', 4)
''')

conexao.commit()

Para confirmar que o álbum foi realmente criado, consulte de volta os últimos registros da tabela:

In [ ]:
cursor.execute("SELECT * FROM albums ORDER BY AlbumId DESC LIMIT 3")
print(cursor.fetchall())

cursor.close()
conexao.close()

### ✏️ Atividade Prática 1 — Sua vez de programar (Create)

**Contextualização:** a Chinook Records fechou uma parceria para remasterizar álbuns antigos do catálogo. O primeiro da lista é um álbum novo da banda **AC/DC** (`ArtistId` 1, já cadastrada em `artists`), que precisa entrar na tabela `albums` antes de a equipe de marketing anunciar o relançamento.

**Comando:** conecte no `chinook.db`, e insira na tabela `albums` um registro com `Title` = `'Back in Black (Remaster)'` e `ArtistId` = `1`. Depois, confirme com um `SELECT` que o álbum aparece na tabela. Use o mesmo padrão do exemplo acima (conectar → cursor → `INSERT` → `commit` → `SELECT` de confirmação → fechar).

In [ ]:
# escreva seu código aqui

import pyodbc

# Conectar ao banco de dados
dados_conexao = ("Driver={SQLite3 ODBC Driver};Server=localhost;Database=dataset/chinook.db")

conexao = pyodbc.connect(dados_conexao)

# Criar cursor
cursor = conexao.cursor()

# Insere um registro e comita
cursor.execute('''
    INSERT INTO albums (Title, ArtistId)
    VALUES (?, ?)
''', ('Back in Black (Remaster)', 1))


cursor.execute(
    "INSERT INTO albums (Title, ArtistId) VALUES (?, ?)", 
    ("Back in Black (Remaster) teste", 2)
    )

conexao.commit()

# Faz uma consulta e encerra a conexão
cursor.execute("SELECT * FROM albums ORDER BY AlbumId DESC LIMIT 3")
print(cursor.fetchall())

cursor.close()
conexao.close()

## Passo 4 — Lendo dados com Read (2 formas)

Você já leu dados no Passo 2, mas existem duas formas de fazer isso com o `pyodbc`, e vale a pena conhecer as duas:

1. **Manual**: `cursor.execute()` + `cursor.fetchall()` — você mesmo monta o DataFrame a partir do resultado.
2. **Direto com Pandas**: `pd.read_sql()` — o Pandas já devolve o resultado pronto como DataFrame, numa linha só.

Comece pela forma manual, lendo a tabela `customers` do `chinook.db`:

In [ ]:
import pyodbc

dados_conexao = ("Driver={SQLite3 ODBC Driver};Server=localhost;Database=dataset/chinook.db")

conexao = pyodbc.connect(dados_conexao)

cursor = conexao.cursor()

cursor.execute("SELECT * FROM customers")

valores = cursor.fetchall()
descricao = cursor.description
cursor.close()

Repare que o `cursor.close()` acima já aconteceu, mas `valores` e `descricao` continuam existindo — eles foram guardados em variáveis Python assim que o `execute`/`fetchall` rodou, então já não dependem mais do cursor estar aberto. Fechar o cursor só impede que você rode um *novo* comando SQL nele; não apaga o que você já salvou em variáveis.

O `cursor.description` guarda os metadados das colunas retornadas (nome, tipo, etc.) — não os dados em si. Para montar um DataFrame, você precisa dos nomes das colunas separadamente:

In [ ]:
colunas = [tupla[0] for tupla in descricao]
print(colunas)

In [ ]:
import pandas as pd

tabela_clientes = pd.DataFrame.from_records(valores, columns=colunas)
display(tabela_clientes.head())

`pd.DataFrame.from_records()` monta uma tabela a partir de uma lista de tuplas (exatamente o formato que `fetchall()` devolve) — é equivalente ao `pd.DataFrame(valores, columns=colunas)` que você já conhece, só que com um nome que deixa claro que a origem são "registros" (linhas de um banco de dados), não um dicionário.

In [ ]:
conexao.close()

Agora a forma direta, usando `pd.read_sql()` — o mesmo resultado, em muito menos código. Aqui a conexão é aberta com o módulo `sqlite3` (nativo do Python, sem precisar de driver ODBC nenhum) em vez do `pyodbc`, porque o Pandas já sabe conversar direto com um arquivo SQLite.

**Se isso funciona sem instalar nada, por que você instalou `pyodbc` + o driver no Passo 0?** Porque esse atalho com `sqlite3` só existe porque o banco É um arquivo SQLite. Se este fosse um SQL Server, MySQL ou o PostgreSQL das Semanas 08-10, esse módulo nativo não serviria — você precisaria do `pyodbc` (ou do `psycopg2`, específico do Postgres) do mesmo jeito. O Passo 0 vale para qualquer banco real que você for usar depois do curso; este atalho vale só para SQLite.

In [ ]:
import pandas as pd
import sqlite3

conexao = sqlite3.connect("dataset/chinook.db")

tabela_clientes_outra = pd.read_sql("SELECT * FROM customers", conexao)
display(tabela_clientes_outra)

conexao.close()

In [30]:
display(tabela_clientes_outra.head())

,CustomerId,FirstName,LastName,Company,Address,City,State,Country,PostalCode,Phone,Fax,Email,SupportRepId
0,1,Luís,Gonçalves,Embraer - Empresa Brasileira de Aeronáutica S.A.,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,+55 (12) 3923-5555,+55 (12) 3923-5566,luisg@embraer.com.br,3
1,2,Leonie,Köhler,NaN,Theodor-Heuss-Straße 34,Stuttgart,NaN,Germany,70174,+49 0711 2842222,NaN,leonekohler@surfeu.de,5
2,3,François,Tremblay,NaN,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,+1 (514) 721-4711,NaN,ftremblay@gmail.com,3
3,4,Bjørn,Hansen,NaN,Ullevålsveien 14,Oslo,NaN,Norway,0171,+47 22 44 22 22,NaN,bjorn.hansen@yahoo.no,4
4,5,František,Wichterlová,JetBrains s.r.o.,Klanova 9/506,Prague,NaN,Czech Republic,14700,+420 2 4172 5555,+420 2 4172 5555,frantisekw@jetbrains.com,4

### ✏️ Atividade Prática 2 — Sua vez de programar (Read)

**Contextualização:** o time de suporte da Chinook Records precisa entrar em contato com todos os clientes brasileiros para avisar sobre uma promoção. Eles pediram uma lista com nome e e-mail desses clientes.

**Comando:** usando a forma que você preferir (manual com `cursor`, ou direto com `pd.read_sql`), consulte na tabela `customers` do `chinook.db` as colunas `FirstName`, `LastName` e `Email` de todos os clientes onde `Country = 'Brazil'`.

In [35]:
# escreva seu código aqui
import pandas as pd
import sqlite3

conexao = sqlite3.connect("dataset/chinook.db")

tabela_lista_email = pd.read_sql("SELECT FirstName, LastName, Email, Country FROM customers WHERE Country = 'Brazil'", conexao)
display(tabela_lista_email)

conexao.close()

   FirstName   LastName                          Email Country
0       Luís  Gonçalves           luisg@embraer.com.br  Brazil
1    Eduardo    Martins       eduardo@woodstock.com.br  Brazil
2  Alexandre      Rocha               alero@uol.com.br  Brazil
3    Roberto    Almeida  roberto.almeida@riotur.gov.br  Brazil
4   Fernanda      Ramos       fernadaramos4@uol.com.br  Brazil

## Passo 5 — Atualizando registros (Update)

O comando SQL `UPDATE` altera valores de linhas que já existem. Abaixo, o e-mail de um cliente cadastrado no `chinook.db` é corrigido.

In [36]:
import pyodbc

dados_conexao = ("Driver={SQLite3 ODBC Driver};Server=localhost;Database=dataset/chinook.db")

conexao = pyodbc.connect(dados_conexao)

cursor = conexao.cursor()

In [37]:
cursor.execute('''
UPDATE customers SET Email='lira@embraer.com.br' WHERE Email='luisg@embraer.com.br'
''') # executar o comando SQL

conexao.commit() # perpetuar no banco as alterações

cursor.close()
conexao.close() # finalizar a conexão

### ✏️ Atividade Prática 3 — Sua vez de programar (Update)

**Contextualização:** a cliente de `CustomerId` 2 (`leonekohler@surfeu.de`) ligou avisando que mudou de cidade e agora mora em `'Berlin'`.

**Comando:** conecte no `chinook.db` e atualize a coluna `City` da tabela `customers` para `'Berlin'`, filtrando por `CustomerId = 2`. Depois, confirme com um `SELECT` que a cidade mudou.

In [2]:
import pyodbc

dados_conexao = ("Driver={SQLite3 ODBC Driver};Server=localhost;Database=dataset/chinook.db")

conexao = pyodbc.connect(dados_conexao)

cursor = conexao.cursor()

cursor.execute('''
UPDATE customers SET City='Berlin' WHERE CustomerId = 2
''') # executar o comando SQL

conexao.commit() # perpetuar no banco as alterações

cursor.execute('''
SELECT * FROM customers WHERE CustomerId = 2
''') # executar o comando SQL
print(cursor.fetchall())

cursor.close()
conexao.close() # finalizar a conexão

[(2, 'Leonie', 'Köhler', None, 'Theodor-Heuss-Straße 34', 'Berlin', None, 'Germany', '70174', '+49 0711 2842222', None, 'leonekohler@surfeu.de', 5)]

## Passo 6 — Removendo registros (Delete)

O comando SQL `DELETE` remove linhas inteiras de uma tabela. Abaixo, um álbum é removido do `chinook.db` pelo seu `AlbumId`.

**⚠️ Cuidado com o `DELETE` sem `WHERE`** — sem essa cláusula, o comando apaga a tabela inteira, não só uma linha.

In [8]:
import pyodbc

dados_conexao = ("Driver={SQLite3 ODBC Driver};Server=localhost;Database=dataset/chinook.db")

conexao = pyodbc.connect(dados_conexao)

cursor = conexao.cursor()

In [9]:
cursor.execute('''
DELETE FROM albums WHERE AlbumId=2
''')

conexao.commit()

cursor.execute('''
SELECT * FROM albums
''') # executar o comando SQL
print(cursor.fetchall())

cursor.close()
conexao.close()

[(1, 'For Those About To Rock We Salute You', 1), (3, 'Restless and Wild', 2), (4, 'Let There Be Rock', 1), (5, 'Big Ones', 3), (6, 'Jagged Little Pill', 4), (7, 'Facelift', 5), (8, 'Warner 25 Anos', 6), (9, 'Plays Metallica By Four Cellos', 7), (10, 'Audioslave', 8), (11, 'Out Of Exile', 8), (12, 'BackBeat Soundtrack', 9), (13, 'The Best Of Billy Cobham', 10), (14, 'Alcohol Fueled Brewtality Live! [Disc 1]', 11), (15, 'Alcohol Fueled Brewtality Live! [Disc 2]', 11), (16, 'Black Sabbath', 12), (17, 'Black Sabbath Vol. 4 (Remaster)', 12), (18, 'Body Count', 13), (19, 'Chemical Wedding', 14), (20, 'The Best Of Buddy Guy - The Millenium Collection', 15), (21, 'Prenda Minha', 16), (22, 'Sozinho Remix Ao Vivo', 16), (23, 'Minha Historia', 17), (24, 'Afrociberdelia', 18), (25, 'Da Lama Ao Caos', 18), (26, 'Acústico MTV [Live]', 19), (27, 'Cidade Negra - Hits', 19), (28, 'Na Pista', 20), (29, 'Axé Bahia 2001', 21), (30, 'BBC Sessions [Disc 1] [Live]', 22), (31, 'Bongo Fury', 23), (32, 'Carnaval 2001', 21), (33, 'Chill: Brazil (Disc 1)', 24), (34, 'Chill: Brazil (Disc 2)', 6), (35, 'Garage Inc. (Disc 1)', 50), (36, 'Greatest Hits II', 51), (37, 'Greatest Kiss', 52), (38, 'Heart of the Night', 53), (39, 'International Superhits', 54), (40, 'Into The Light', 55), (41, 'Meus Momentos', 56), (42, 'Minha História', 57), (43, 'MK III The Final Concerts [Disc 1]', 58), (44, 'Physical Graffiti [Disc 1]', 22), (45, 'Sambas De Enredo 2001', 21), (46, 'Supernatural', 59), (47, 'The Best of Ed Motta', 37), (48, 'The Essential Miles Davis [Disc 1]', 68), (49, 'The Essential Miles Davis [Disc 2]', 68), (50, 'The Final Concerts (Disc 2)', 58), (51, "Up An' Atom", 69), (52, 'Vinícius De Moraes - Sem Limite', 70), (53, 'Vozes do MPB', 21), (54, 'Chronicle, Vol. 1', 76), (55, 'Chronicle, Vol. 2', 76), (56, 'Cássia Eller - Coleção Sem Limite [Disc 2]', 77), (57, 'Cássia Eller - Sem Limite [Disc 1]', 77), (58, 'Come Taste The Band', 58), (59, 'Deep Purple In Rock', 58), (60, 'Fireball', 58), (61, "Knocking at Your Back Door: The Best Of Deep Purple in the 80's", 58), (62, 'Machine Head', 58), (63, 'Purpendicular', 58), (64, 'Slaves And Masters', 58), (65, 'Stormbringer', 58), (66, 'The Battle Rages On', 58), (67, "Vault: Def Leppard's Greatest Hits", 78), (68, 'Outbreak', 79), (69, 'Djavan Ao Vivo - Vol. 02', 80), (70, 'Djavan Ao Vivo - Vol. 1', 80), (71, 'Elis Regina-Minha História', 41), (72, 'The Cream Of Clapton', 81), (73, 'Unplugged', 81), (74, 'Album Of The Year', 82), (75, 'Angel Dust', 82), (76, 'King For A Day Fool For A Lifetime', 82), (77, 'The Real Thing', 82), (78, 'Deixa Entrar', 83), (79, 'In Your Honor [Disc 1]', 84), (80, 'In Your Honor [Disc 2]', 84), (81, 'One By One', 84), (82, 'The Colour And The Shape', 84), (83, 'My Way: The Best Of Frank Sinatra [Disc 1]', 85), (84, 'Roda De Funk', 86), (85, 'As Canções de Eu Tu Eles', 27), (86, 'Quanta Gente Veio Ver (Live)', 27), (87, 'Quanta Gente Veio ver--Bônus De Carnaval', 27), (88, 'Faceless', 87), (89, 'American Idiot', 54), (90, 'Appetite for Destruction', 88), (91, 'Use Your Illusion I', 88), (92, 'Use Your Illusion II', 88), (93, 'Blue Moods', 89), (94, 'A Matter of Life and Death', 90), (95, 'A Real Dead One', 90), (96, 'A Real Live One', 90), (97, 'Brave New World', 90), (98, 'Dance Of Death', 90), (99, 'Fear Of The Dark', 90), (100, 'Iron Maiden', 90), (101, 'Killers', 90), (102, 'Live After Death', 90), (103, 'Live At Donington 1992 (Disc 1)', 90), (104, 'Live At Donington 1992 (Disc 2)', 90), (105, 'No Prayer For The Dying', 90), (106, 'Piece Of Mind', 90), (107, 'Powerslave', 90), (108, 'Rock In Rio [CD1]', 90), (109, 'Rock In Rio [CD2]', 90), (110, 'Seventh Son of a Seventh Son', 90), (111, 'Somewhere in Time', 90), (112, 'The Number of The Beast', 90), (113, 'The X Factor', 90), (114, 'Virtual XI', 90), (115, 'Sex Machine', 91), (116, 'Emergency On Planet Earth', 92), (117, 'Synkronized', 92), (118, 'The Return Of The Space Cowboy', 92), (119, 'Get Born', 93), (120, 'Are You Experienced?', 94), (121, 'Surfing with the Alien (Remastered)', 95), (122, 'Jorge Ben Jor 25 Anos', 46), (123, 'Jota Quest-1995', 96), (124, 'Cafezinho', 97), (125, 'Living After Midnight', 98), (126, 'Unplugged [Live]', 52), (127, 'BBC Sessions [Disc 2] [Live]', 22), (128, 'Coda', 22), (129, 'Houses Of The Holy', 22), (130, 'In Through The Out Door', 22), (131, 'IV', 22), (132, 'Led Zeppelin I', 22), (133, 'Led Zeppelin II', 22), (134, 'Led Zeppelin III', 22), (135, 'Physical Graffiti [Disc 2]', 22), (136, 'Presence', 22), (137, 'The Song Remains The Same (Disc 1)', 22), (138, 'The Song Remains The Same (Disc 2)', 22), (139, 'A TempestadeTempestade Ou O Livro Dos Dias', 99), (140, 'Mais Do Mesmo', 99), (141, 'Greatest Hits', 100), (142, 'Lulu Santos - RCA 100 Anos De Música - Álbum 01', 101), (143, 'Lulu Santos - RCA 100 Anos De Música - Álbum 02', 101), (144, 'Misplaced Childhood', 102), (145, 'Barulhinho Bom', 103), (146, 'Seek And Shall Find: More Of The Best (1963-1981)', 104), (147, 'The Best Of Men At Work', 105), (148, 'Black Album', 50), (149, 'Garage Inc. (Disc 2)', 50), (150, "Kill 'Em All", 50), (151, 'Load', 50), (152, 'Master Of Puppets', 50), (153, 'ReLoad', 50), (154, 'Ride The Lightning', 50), (155, 'St. Anger', 50), (156, '...And Justice For All', 50), (157, 'Miles Ahead', 68), (158, 'Milton Nascimento Ao Vivo', 42), (159, 'Minas', 42), (160, 'Ace Of Spades', 106), (161, 'Demorou...', 108), (162, 'Motley Crue Greatest Hits', 109), (163, 'From The Muddy Banks Of The Wishkah [Live]', 110), (164, 'Nevermind', 110), (165, 'Compositores', 111), (166, 'Olodum', 112), (167, 'Acústico MTV', 113), (168, 'Arquivo II', 113), (169, 'Arquivo Os Paralamas Do Sucesso', 113), (170, 'Bark at the Moon (Remastered)', 114), (171, 'Blizzard of Ozz', 114), (172, 'Diary of a Madman (Remastered)', 114), (173, 'No More Tears (Remastered)', 114), (174, 'Tribute', 114), (175, 'Walking Into Clarksdale', 115), (176, 'Original Soundtracks 1', 116), (177, 'The Beast Live', 117), (178, 'Live On Two Legs [Live]', 118), (179, 'Pearl Jam', 118), (180, 'Riot Act', 118), (181, 'Ten', 118), (182, 'Vs.', 118), (183, 'Dark Side Of The Moon', 120), (184, 'Os Cães Ladram Mas A Caravana Não Pára', 121), (185, 'Greatest Hits I', 51), (186, 'News Of The World', 51), (187, 'Out Of Time', 122), (188, 'Green', 124), (189, 'New Adventures In Hi-Fi', 124), (190, 'The Best Of R.E.M.: The IRS Years', 124), (191, 'Cesta Básica', 125), (192, 'Raul Seixas', 126), (193, 'Blood Sugar Sex Magik', 127), (194, 'By The Way', 127), (195, 'Californication', 127), (196, 'Retrospective I (1974-1980)', 128), (197, 'Santana - As Years Go By', 59), (198, 'Santana Live', 59), (199, 'Maquinarama', 130), (200, 'O Samba Poconé', 130), (201, 'Judas 0: B-Sides and Rarities', 131), (202, 'Rotten Apples: Greatest Hits', 131), (203, 'A-Sides', 132), (204, 'Morning Dance', 53), (205, 'In Step', 133), (206, 'Core', 134), (207, 'Mezmerize', 135), (208, '[1997] Black Light Syndrome', 136), (209, 'Live [Disc 1]', 137), (210, 'Live [Disc 2]', 137), (211, 'The Singles', 138), (212, 'Beyond Good And Evil', 139), (213, 'Pure Cult: The Best Of The Cult (For Rockers, Ravers, Lovers & Sinners) [UK]', 139), (214, 'The Doors', 140), (215, 'The Police Greatest Hits', 141), (216, 'Hot Rocks, 1964-1971 (Disc 1)', 142), (217, 'No Security', 142), (218, 'Voodoo Lounge', 142), (219, 'Tangents', 143), (220, 'Transmission', 143), (221, 'My Generation - The Very Best Of The Who', 144), (222, 'Serie Sem Limite (Disc 1)', 145), (223, 'Serie Sem Limite (Disc 2)', 145), (224, 'Acústico', 146), (225, 'Volume Dois', 146), (226, 'Battlestar Galactica: The Story So Far', 147), (227, 'Battlestar Galactica, Season 3', 147), (228, 'Heroes, Season 1', 148), (229, 'Lost, Season 3', 149), (230, 'Lost, Season 1', 149), (231, 'Lost, Season 2', 149), (232, 'Achtung Baby', 150), (233, "All That You Can't Leave Behind", 150), (234, 'B-Sides 1980-1990', 150), (235, 'How To Dismantle An Atomic Bomb', 150), (236, 'Pop', 150), (237, 'Rattle And Hum', 150), (238, 'The Best Of 1980-1990', 150), (239, 'War', 150), (240, 'Zooropa', 150), (241, 'UB40 The Best Of - Volume Two [UK]', 151), (242, 'Diver Down', 152), (243, 'The Best Of Van Halen, Vol. I', 152), (244, 'Van Halen', 152), (245, 'Van Halen III', 152), (246, 'Contraband', 153), (247, 'Vinicius De Moraes', 72), (248, 'Ao Vivo [IMPORT]', 155), (249, 'The Office, Season 1', 156), (250, 'The Office, Season 2', 156), (251, 'The Office, Season 3', 156), (252, 'Un-Led-Ed', 157), (253, 'Battlestar Galactica (Classic), Season 1', 158), (254, 'Aquaman', 159), (255, 'Instant Karma: The Amnesty International Campaign to Save Darfur', 150), (256, 'Speak of the Devil', 114), (257, '20th Century Masters - The Millennium Collection: The Best of Scorpions', 179), (258, 'House of Pain', 180), (259, 'Radio Brasil (O Som da Jovem Vanguarda) - Seleccao de Henrique Amaro', 36), (260, 'Cake: B-Sides and Rarities', 196), (261, 'LOST, Season 4', 149), (262, 'Quiet Songs', 197), (263, 'Muso Ko', 198), (264, 'Realize', 199), (265, 'Every Kind of Light', 200), (266, 'Duos II', 201), (267, 'Worlds', 202), (268, 'The Best of Beethoven', 203), (269, 'Temple of the Dog', 204), (270, 'Carry On', 205), (271, 'Revelations', 8), (272, 'Adorate Deum: Gregorian Chant from the Proper of the Mass', 206), (273, 'Allegri: Miserere', 207), (274, 'Pachelbel: Canon & Gigue', 208), (275, 'Vivaldi: The Four Seasons', 209), (276, 'Bach: Violin Concertos', 210), (277, 'Bach: Goldberg Variations', 211), (278, 'Bach: The Cello Suites', 212), (279, 'Handel: The Messiah (Highlights)', 213), (280, 'The World of Classical Favourites', 214), (281, 'Sir Neville Marriner: A Celebration', 215), (282, 'Mozart: Wind Concertos', 216), (283, 'Haydn: Symphonies 99 - 104', 217), (284, 'Beethoven: Symhonies Nos. 5 & 6', 218), (285, 'A Soprano Inspired', 219), (286, 'Great Opera Choruses', 220), (287, 'Wagner: Favourite Overtures', 221), (288, 'Fauré: Requiem, Ravel: Pavane & Others', 222), (289, 'Tchaikovsky: The Nutcracker', 223), (290, 'The Last Night of the Proms', 224), (291, 'Puccini: Madama Butterfly - Highlights', 225), (292, 'Holst: The Planets, Op. 32 & Vaughan Williams: Fantasies', 226), (293, "Pavarotti's Opera Made Easy", 227), (294, "Great Performances - Barber's Adagio and Other Romantic Favorites for Strings", 228), (295, 'Carmina Burana', 229), (296, 'A Copland Celebration, Vol. I', 230), (297, 'Bach: Toccata & Fugue in D Minor', 231), (298, 'Prokofiev: Symphony No.1', 232), (299, 'Scheherazade', 233), (300, 'Bach: The Brandenburg Concertos', 234), (301, 'Chopin: Piano Concertos Nos. 1 & 2', 235), (302, 'Mascagni: Cavalleria Rusticana', 236), (303, 'Sibelius: Finlandia', 237), (304, 'Beethoven Piano Sonatas: Moonlight & Pastorale', 238), (305, 'Great Recordings of the Century - Mahler: Das Lied von der Erde', 240), (306, 'Elgar: Cello Concerto & Vaughan Williams: Fantasias', 241), (307, 'Adams, John: The Chairman Dances', 242), (308, "Tchaikovsky: 1812 Festival Overture, Op.49, Capriccio Italien & Beethoven: Wellington's Victory", 243), (309, 'Palestrina: Missa Papae Marcelli & Allegri: Miserere', 244), (310, 'Prokofiev: Romeo & Juliet', 245), (311, 'Strauss: Waltzes', 226), (312, 'Berlioz: Symphonie Fantastique', 245), (313, 'Bizet: Carmen Highlights', 246), (314, 'English Renaissance', 247), (315, 'Handel: Music for the Royal Fireworks (Original Version 1749)', 208), (316, 'Grieg: Peer Gynt Suites & Sibelius: Pelléas et Mélisande', 248), (317, 'Mozart Gala: Famous Arias', 249), (318, 'SCRIABIN: Vers la flamme', 250), (319, 'Armada: Music from the Courts of England and Spain', 251), (320, 'Mozart: Symphonies Nos. 40 & 41', 248), (321, 'Back to Black', 252), (322, 'Frank', 252), (323, 'Carried to Dust (Bonus Track Version)', 253), (324, "Beethoven: Symphony No. 6 'Pastoral' Etc.", 254), (325, 'Bartok: Violin & Viola Concertos', 255), (326, "Mendelssohn: A Midsummer Night's Dream", 256), (327, 'Bach: Orchestral Suites Nos. 1 - 4', 257), (328, 'Charpentier: Divertissements, Airs & Concerts', 258), (329, 'South American Getaway', 259), (330, 'Górecki: Symphony No. 3', 260), (331, 'Purcell: The Fairy Queen', 261), (332, 'The Ultimate Relexation Album', 262), (333, 'Purcell: Music for the Queen Mary', 263), (334, 'Weill: The Seven Deadly Sins', 264), (335, 'J.S. Bach: Chaconne, Suite in E Minor, Partita in E Major & Prelude, Fugue and Allegro', 265), (336, 'Prokofiev: Symphony No.5 & Stravinksy: Le Sacre Du Printemps', 248), (337, 'Szymanowski: Piano Works, Vol. 1', 266), (338, 'Nielsen: The Six Symphonies', 267), (339, "Great Recordings of the Century: Paganini's 24 Caprices", 268), (340, "Liszt - 12 Études D'Execution Transcendante", 269), (341, 'Great Recordings of the Century - Shubert: Schwanengesang, 4 Lieder', 270), (342, 'Locatelli: Concertos for Violin, Strings and Continuo, Vol. 3', 271), (343, 'Respighi:Pines of Rome', 226), (344, "Schubert: The Late String Quartets & String Quintet (3 CD's)", 272), (345, "Monteverdi: L'Orfeo", 273), (346, 'Mozart: Chamber Music', 274), (347, 'Koyaanisqatsi (Soundtrack from the Motion Picture)', 275), (348, 'Lira Rock', 4), (349, 'Back in Black (Remaster)', 1), (350, 'Back in Black (Remaster)', 1), (351, 'Back in Black (Remaster)', 1), (352, 'Back in Black (Remaster)', 1), (353, 'Back in Black (Remaster)', 1), (354, 'Back in Black (Remaster)', 1), (355, 'Back in Black (Remaster) teste', 2)]

### ✏️ Atividade Prática 4 — Sua vez de programar (Delete)

**Contextualização:** a parceria de remasterização do Passo 3 (Atividade 1) foi cancelada — a Chinook Records pediu para remover o álbum `'Back in Black (Remaster)'` que você cadastrou, já que a versão final saiu diferente da testada.

**Comando:** conecte no `chinook.db` e remova, da tabela `albums`, o registro com `Title = 'Back in Black (Remaster)'`. Depois, confirme com um `SELECT` que ele não aparece mais.

In [10]:
# Conexão
import pyodbc

dados_conexao = ("Driver={SQLite3 ODBC Driver};Server=localhost;Database=dataset/chinook.db")

conexao = pyodbc.connect(dados_conexao)

cursor = conexao.cursor()

# Remoção
cursor.execute('''
DELETE FROM albums WHERE Title= 'Back in Black (Remaster)'
''')

conexao.commit()

# Consulta e fechamento do cursor/conexão
cursor.execute('''
SELECT * FROM albums
''') # executar o comando SQL
print(cursor.fetchall())

cursor.close()
conexao.close()

[(1, 'For Those About To Rock We Salute You', 1), (3, 'Restless and Wild', 2), (4, 'Let There Be Rock', 1), (5, 'Big Ones', 3), (6, 'Jagged Little Pill', 4), (7, 'Facelift', 5), (8, 'Warner 25 Anos', 6), (9, 'Plays Metallica By Four Cellos', 7), (10, 'Audioslave', 8), (11, 'Out Of Exile', 8), (12, 'BackBeat Soundtrack', 9), (13, 'The Best Of Billy Cobham', 10), (14, 'Alcohol Fueled Brewtality Live! [Disc 1]', 11), (15, 'Alcohol Fueled Brewtality Live! [Disc 2]', 11), (16, 'Black Sabbath', 12), (17, 'Black Sabbath Vol. 4 (Remaster)', 12), (18, 'Body Count', 13), (19, 'Chemical Wedding', 14), (20, 'The Best Of Buddy Guy - The Millenium Collection', 15), (21, 'Prenda Minha', 16), (22, 'Sozinho Remix Ao Vivo', 16), (23, 'Minha Historia', 17), (24, 'Afrociberdelia', 18), (25, 'Da Lama Ao Caos', 18), (26, 'Acústico MTV [Live]', 19), (27, 'Cidade Negra - Hits', 19), (28, 'Na Pista', 20), (29, 'Axé Bahia 2001', 21), (30, 'BBC Sessions [Disc 1] [Live]', 22), (31, 'Bongo Fury', 23), (32, 'Carnaval 2001', 21), (33, 'Chill: Brazil (Disc 1)', 24), (34, 'Chill: Brazil (Disc 2)', 6), (35, 'Garage Inc. (Disc 1)', 50), (36, 'Greatest Hits II', 51), (37, 'Greatest Kiss', 52), (38, 'Heart of the Night', 53), (39, 'International Superhits', 54), (40, 'Into The Light', 55), (41, 'Meus Momentos', 56), (42, 'Minha História', 57), (43, 'MK III The Final Concerts [Disc 1]', 58), (44, 'Physical Graffiti [Disc 1]', 22), (45, 'Sambas De Enredo 2001', 21), (46, 'Supernatural', 59), (47, 'The Best of Ed Motta', 37), (48, 'The Essential Miles Davis [Disc 1]', 68), (49, 'The Essential Miles Davis [Disc 2]', 68), (50, 'The Final Concerts (Disc 2)', 58), (51, "Up An' Atom", 69), (52, 'Vinícius De Moraes - Sem Limite', 70), (53, 'Vozes do MPB', 21), (54, 'Chronicle, Vol. 1', 76), (55, 'Chronicle, Vol. 2', 76), (56, 'Cássia Eller - Coleção Sem Limite [Disc 2]', 77), (57, 'Cássia Eller - Sem Limite [Disc 1]', 77), (58, 'Come Taste The Band', 58), (59, 'Deep Purple In Rock', 58), (60, 'Fireball', 58), (61, "Knocking at Your Back Door: The Best Of Deep Purple in the 80's", 58), (62, 'Machine Head', 58), (63, 'Purpendicular', 58), (64, 'Slaves And Masters', 58), (65, 'Stormbringer', 58), (66, 'The Battle Rages On', 58), (67, "Vault: Def Leppard's Greatest Hits", 78), (68, 'Outbreak', 79), (69, 'Djavan Ao Vivo - Vol. 02', 80), (70, 'Djavan Ao Vivo - Vol. 1', 80), (71, 'Elis Regina-Minha História', 41), (72, 'The Cream Of Clapton', 81), (73, 'Unplugged', 81), (74, 'Album Of The Year', 82), (75, 'Angel Dust', 82), (76, 'King For A Day Fool For A Lifetime', 82), (77, 'The Real Thing', 82), (78, 'Deixa Entrar', 83), (79, 'In Your Honor [Disc 1]', 84), (80, 'In Your Honor [Disc 2]', 84), (81, 'One By One', 84), (82, 'The Colour And The Shape', 84), (83, 'My Way: The Best Of Frank Sinatra [Disc 1]', 85), (84, 'Roda De Funk', 86), (85, 'As Canções de Eu Tu Eles', 27), (86, 'Quanta Gente Veio Ver (Live)', 27), (87, 'Quanta Gente Veio ver--Bônus De Carnaval', 27), (88, 'Faceless', 87), (89, 'American Idiot', 54), (90, 'Appetite for Destruction', 88), (91, 'Use Your Illusion I', 88), (92, 'Use Your Illusion II', 88), (93, 'Blue Moods', 89), (94, 'A Matter of Life and Death', 90), (95, 'A Real Dead One', 90), (96, 'A Real Live One', 90), (97, 'Brave New World', 90), (98, 'Dance Of Death', 90), (99, 'Fear Of The Dark', 90), (100, 'Iron Maiden', 90), (101, 'Killers', 90), (102, 'Live After Death', 90), (103, 'Live At Donington 1992 (Disc 1)', 90), (104, 'Live At Donington 1992 (Disc 2)', 90), (105, 'No Prayer For The Dying', 90), (106, 'Piece Of Mind', 90), (107, 'Powerslave', 90), (108, 'Rock In Rio [CD1]', 90), (109, 'Rock In Rio [CD2]', 90), (110, 'Seventh Son of a Seventh Son', 90), (111, 'Somewhere in Time', 90), (112, 'The Number of The Beast', 90), (113, 'The X Factor', 90), (114, 'Virtual XI', 90), (115, 'Sex Machine', 91), (116, 'Emergency On Planet Earth', 92), (117, 'Synkronized', 92), (118, 'The Return Of The Space Cowboy', 92), (119, 'Get Born', 93), (120, 'Are You Experienced?', 94), (121, 'Surfing with the Alien (Remastered)', 95), (122, 'Jorge Ben Jor 25 Anos', 46), (123, 'Jota Quest-1995', 96), (124, 'Cafezinho', 97), (125, 'Living After Midnight', 98), (126, 'Unplugged [Live]', 52), (127, 'BBC Sessions [Disc 2] [Live]', 22), (128, 'Coda', 22), (129, 'Houses Of The Holy', 22), (130, 'In Through The Out Door', 22), (131, 'IV', 22), (132, 'Led Zeppelin I', 22), (133, 'Led Zeppelin II', 22), (134, 'Led Zeppelin III', 22), (135, 'Physical Graffiti [Disc 2]', 22), (136, 'Presence', 22), (137, 'The Song Remains The Same (Disc 1)', 22), (138, 'The Song Remains The Same (Disc 2)', 22), (139, 'A TempestadeTempestade Ou O Livro Dos Dias', 99), (140, 'Mais Do Mesmo', 99), (141, 'Greatest Hits', 100), (142, 'Lulu Santos - RCA 100 Anos De Música - Álbum 01', 101), (143, 'Lulu Santos - RCA 100 Anos De Música - Álbum 02', 101), (144, 'Misplaced Childhood', 102), (145, 'Barulhinho Bom', 103), (146, 'Seek And Shall Find: More Of The Best (1963-1981)', 104), (147, 'The Best Of Men At Work', 105), (148, 'Black Album', 50), (149, 'Garage Inc. (Disc 2)', 50), (150, "Kill 'Em All", 50), (151, 'Load', 50), (152, 'Master Of Puppets', 50), (153, 'ReLoad', 50), (154, 'Ride The Lightning', 50), (155, 'St. Anger', 50), (156, '...And Justice For All', 50), (157, 'Miles Ahead', 68), (158, 'Milton Nascimento Ao Vivo', 42), (159, 'Minas', 42), (160, 'Ace Of Spades', 106), (161, 'Demorou...', 108), (162, 'Motley Crue Greatest Hits', 109), (163, 'From The Muddy Banks Of The Wishkah [Live]', 110), (164, 'Nevermind', 110), (165, 'Compositores', 111), (166, 'Olodum', 112), (167, 'Acústico MTV', 113), (168, 'Arquivo II', 113), (169, 'Arquivo Os Paralamas Do Sucesso', 113), (170, 'Bark at the Moon (Remastered)', 114), (171, 'Blizzard of Ozz', 114), (172, 'Diary of a Madman (Remastered)', 114), (173, 'No More Tears (Remastered)', 114), (174, 'Tribute', 114), (175, 'Walking Into Clarksdale', 115), (176, 'Original Soundtracks 1', 116), (177, 'The Beast Live', 117), (178, 'Live On Two Legs [Live]', 118), (179, 'Pearl Jam', 118), (180, 'Riot Act', 118), (181, 'Ten', 118), (182, 'Vs.', 118), (183, 'Dark Side Of The Moon', 120), (184, 'Os Cães Ladram Mas A Caravana Não Pára', 121), (185, 'Greatest Hits I', 51), (186, 'News Of The World', 51), (187, 'Out Of Time', 122), (188, 'Green', 124), (189, 'New Adventures In Hi-Fi', 124), (190, 'The Best Of R.E.M.: The IRS Years', 124), (191, 'Cesta Básica', 125), (192, 'Raul Seixas', 126), (193, 'Blood Sugar Sex Magik', 127), (194, 'By The Way', 127), (195, 'Californication', 127), (196, 'Retrospective I (1974-1980)', 128), (197, 'Santana - As Years Go By', 59), (198, 'Santana Live', 59), (199, 'Maquinarama', 130), (200, 'O Samba Poconé', 130), (201, 'Judas 0: B-Sides and Rarities', 131), (202, 'Rotten Apples: Greatest Hits', 131), (203, 'A-Sides', 132), (204, 'Morning Dance', 53), (205, 'In Step', 133), (206, 'Core', 134), (207, 'Mezmerize', 135), (208, '[1997] Black Light Syndrome', 136), (209, 'Live [Disc 1]', 137), (210, 'Live [Disc 2]', 137), (211, 'The Singles', 138), (212, 'Beyond Good And Evil', 139), (213, 'Pure Cult: The Best Of The Cult (For Rockers, Ravers, Lovers & Sinners) [UK]', 139), (214, 'The Doors', 140), (215, 'The Police Greatest Hits', 141), (216, 'Hot Rocks, 1964-1971 (Disc 1)', 142), (217, 'No Security', 142), (218, 'Voodoo Lounge', 142), (219, 'Tangents', 143), (220, 'Transmission', 143), (221, 'My Generation - The Very Best Of The Who', 144), (222, 'Serie Sem Limite (Disc 1)', 145), (223, 'Serie Sem Limite (Disc 2)', 145), (224, 'Acústico', 146), (225, 'Volume Dois', 146), (226, 'Battlestar Galactica: The Story So Far', 147), (227, 'Battlestar Galactica, Season 3', 147), (228, 'Heroes, Season 1', 148), (229, 'Lost, Season 3', 149), (230, 'Lost, Season 1', 149), (231, 'Lost, Season 2', 149), (232, 'Achtung Baby', 150), (233, "All That You Can't Leave Behind", 150), (234, 'B-Sides 1980-1990', 150), (235, 'How To Dismantle An Atomic Bomb', 150), (236, 'Pop', 150), (237, 'Rattle And Hum', 150), (238, 'The Best Of 1980-1990', 150), (239, 'War', 150), (240, 'Zooropa', 150), (241, 'UB40 The Best Of - Volume Two [UK]', 151), (242, 'Diver Down', 152), (243, 'The Best Of Van Halen, Vol. I', 152), (244, 'Van Halen', 152), (245, 'Van Halen III', 152), (246, 'Contraband', 153), (247, 'Vinicius De Moraes', 72), (248, 'Ao Vivo [IMPORT]', 155), (249, 'The Office, Season 1', 156), (250, 'The Office, Season 2', 156), (251, 'The Office, Season 3', 156), (252, 'Un-Led-Ed', 157), (253, 'Battlestar Galactica (Classic), Season 1', 158), (254, 'Aquaman', 159), (255, 'Instant Karma: The Amnesty International Campaign to Save Darfur', 150), (256, 'Speak of the Devil', 114), (257, '20th Century Masters - The Millennium Collection: The Best of Scorpions', 179), (258, 'House of Pain', 180), (259, 'Radio Brasil (O Som da Jovem Vanguarda) - Seleccao de Henrique Amaro', 36), (260, 'Cake: B-Sides and Rarities', 196), (261, 'LOST, Season 4', 149), (262, 'Quiet Songs', 197), (263, 'Muso Ko', 198), (264, 'Realize', 199), (265, 'Every Kind of Light', 200), (266, 'Duos II', 201), (267, 'Worlds', 202), (268, 'The Best of Beethoven', 203), (269, 'Temple of the Dog', 204), (270, 'Carry On', 205), (271, 'Revelations', 8), (272, 'Adorate Deum: Gregorian Chant from the Proper of the Mass', 206), (273, 'Allegri: Miserere', 207), (274, 'Pachelbel: Canon & Gigue', 208), (275, 'Vivaldi: The Four Seasons', 209), (276, 'Bach: Violin Concertos', 210), (277, 'Bach: Goldberg Variations', 211), (278, 'Bach: The Cello Suites', 212), (279, 'Handel: The Messiah (Highlights)', 213), (280, 'The World of Classical Favourites', 214), (281, 'Sir Neville Marriner: A Celebration', 215), (282, 'Mozart: Wind Concertos', 216), (283, 'Haydn: Symphonies 99 - 104', 217), (284, 'Beethoven: Symhonies Nos. 5 & 6', 218), (285, 'A Soprano Inspired', 219), (286, 'Great Opera Choruses', 220), (287, 'Wagner: Favourite Overtures', 221), (288, 'Fauré: Requiem, Ravel: Pavane & Others', 222), (289, 'Tchaikovsky: The Nutcracker', 223), (290, 'The Last Night of the Proms', 224), (291, 'Puccini: Madama Butterfly - Highlights', 225), (292, 'Holst: The Planets, Op. 32 & Vaughan Williams: Fantasies', 226), (293, "Pavarotti's Opera Made Easy", 227), (294, "Great Performances - Barber's Adagio and Other Romantic Favorites for Strings", 228), (295, 'Carmina Burana', 229), (296, 'A Copland Celebration, Vol. I', 230), (297, 'Bach: Toccata & Fugue in D Minor', 231), (298, 'Prokofiev: Symphony No.1', 232), (299, 'Scheherazade', 233), (300, 'Bach: The Brandenburg Concertos', 234), (301, 'Chopin: Piano Concertos Nos. 1 & 2', 235), (302, 'Mascagni: Cavalleria Rusticana', 236), (303, 'Sibelius: Finlandia', 237), (304, 'Beethoven Piano Sonatas: Moonlight & Pastorale', 238), (305, 'Great Recordings of the Century - Mahler: Das Lied von der Erde', 240), (306, 'Elgar: Cello Concerto & Vaughan Williams: Fantasias', 241), (307, 'Adams, John: The Chairman Dances', 242), (308, "Tchaikovsky: 1812 Festival Overture, Op.49, Capriccio Italien & Beethoven: Wellington's Victory", 243), (309, 'Palestrina: Missa Papae Marcelli & Allegri: Miserere', 244), (310, 'Prokofiev: Romeo & Juliet', 245), (311, 'Strauss: Waltzes', 226), (312, 'Berlioz: Symphonie Fantastique', 245), (313, 'Bizet: Carmen Highlights', 246), (314, 'English Renaissance', 247), (315, 'Handel: Music for the Royal Fireworks (Original Version 1749)', 208), (316, 'Grieg: Peer Gynt Suites & Sibelius: Pelléas et Mélisande', 248), (317, 'Mozart Gala: Famous Arias', 249), (318, 'SCRIABIN: Vers la flamme', 250), (319, 'Armada: Music from the Courts of England and Spain', 251), (320, 'Mozart: Symphonies Nos. 40 & 41', 248), (321, 'Back to Black', 252), (322, 'Frank', 252), (323, 'Carried to Dust (Bonus Track Version)', 253), (324, "Beethoven: Symphony No. 6 'Pastoral' Etc.", 254), (325, 'Bartok: Violin & Viola Concertos', 255), (326, "Mendelssohn: A Midsummer Night's Dream", 256), (327, 'Bach: Orchestral Suites Nos. 1 - 4', 257), (328, 'Charpentier: Divertissements, Airs & Concerts', 258), (329, 'South American Getaway', 259), (330, 'Górecki: Symphony No. 3', 260), (331, 'Purcell: The Fairy Queen', 261), (332, 'The Ultimate Relexation Album', 262), (333, 'Purcell: Music for the Queen Mary', 263), (334, 'Weill: The Seven Deadly Sins', 264), (335, 'J.S. Bach: Chaconne, Suite in E Minor, Partita in E Major & Prelude, Fugue and Allegro', 265), (336, 'Prokofiev: Symphony No.5 & Stravinksy: Le Sacre Du Printemps', 248), (337, 'Szymanowski: Piano Works, Vol. 1', 266), (338, 'Nielsen: The Six Symphonies', 267), (339, "Great Recordings of the Century: Paganini's 24 Caprices", 268), (340, "Liszt - 12 Études D'Execution Transcendante", 269), (341, 'Great Recordings of the Century - Shubert: Schwanengesang, 4 Lieder', 270), (342, 'Locatelli: Concertos for Violin, Strings and Continuo, Vol. 3', 271), (343, 'Respighi:Pines of Rome', 226), (344, "Schubert: The Late String Quartets & String Quintet (3 CD's)", 272), (345, "Monteverdi: L'Orfeo", 273), (346, 'Mozart: Chamber Music', 274), (347, 'Koyaanisqatsi (Soundtrack from the Motion Picture)', 275), (348, 'Lira Rock', 4), (355, 'Back in Black (Remaster) teste', 2)]

### ✅ O que você fez até aqui

- Instalou a biblioteca `pyodbc` e o driver ODBC do SQLite no seu computador (Passo 0).
- Entendeu quando faz sentido integrar Python e SQL (Passo 1).
- Conectou o Python a um banco SQLite de ponta a ponta e leu dados de 2 formas — manual e com `pd.read_sql` (Passos 2 e 4).
- Fez o CRUD completo por código: `INSERT` (Passo 3), `UPDATE` (Passo 5) e `DELETE` (Passo 6), praticando cada operação sozinho nas Atividades 1 a 4.